[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "cd ../.. && npm install",
  "cd apps/backend && npm install",
  "npx prisma generate --schema=../../prisma/schema.prisma"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma migrate deploy --schema=../../prisma/schema.prisma && node dist/main.js"

