[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd ../.. && pnpm install --frozen-lockfile",
  "cd apps/backend && npx prisma generate --schema=../../prisma/schema.prisma"
]

[phases.build]
cmds = ["cd apps/backend && pnpm run build"]

[start]
cmd = "cd apps/backend && npx prisma migrate deploy --schema=../../prisma/schema.prisma && node dist/main.js"

